project_id: ""
region: ""
environment: "dev"

# Medallion Storage Layers
storage_layers:
  - name: ""
    storage_class: "STANDARD"
    versioning: true
  - name: ""
    storage_class: "STANDARD"
    versioning: false
  - name: ""
    storage_class: "STANDARD"
    versioning: false

# Cloud Composer (Airflow Environment) Configuration
composer_env:
  name: ""
  environment_size: "ENVIRONMENT_SIZE_SMALL"
  image_version: "composer-3-airflow-2.11.1"
  service_account_name: ""
  pypi_packages:
    pulumi: ">=3.0.0"
    pandas: ">=2.0.0"
    scikit-learn: ">=1.0.0"